title: King's Blog
author: King
email: Jinxuxin2017@gmail.com
description: share idear.

# social links
twitter_username: your-twitter-handle
github_username:  jinxuxin2007
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
